manipulator_controller:  # 机器人控制器配置
  type: position_controllers/JointTrajectoryController  # 控制器类型
  joints:  # 关节列表
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  gains:
    joint1:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7