manipulator_controller:  # 机器人控制器配置
  type: position_controllers/JointTrajectoryController  # 控制器类型
  joints:  # 关节列表
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  gains:
    joint1: {p: 100.0, i: 500.0, d: 10.0, i_clamp_max: 500.0}  # 关节1的PID参数
    joint2: {p: 100.0, i: 500.0, d: 10.0, i_clamp_max: 500.0}
    joint3: {p: 100.0, i: 500.0, d: 10.0, i_clamp_max: 500.0}
    joint4: {p: 100.0, i: 500.0, d: 10.0, i_clamp_max: 500.0}
    joint5: {p: 100.0, i: 500.0, d: 10.0, i_clamp_max: 500.0}
    joint6: {p: 100.0, i: 500.0, d: 10.0, i_clamp_max: 500.0}
    joint7: {p: 100.0, i: 500.0, d: 10.0, i_clamp_max: 500.0}
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7